/**:
  ros__parameters:
    setting_debug_mode:
      # setting visualizer
      using_rviz: false
      rviz_file: display.rviz
      using_rqt: false
      # setting recorder
      using_feedback_recorder: false
      using_footStep_recorder: false
      using_walkingPattern_recorder: false
      using_walkingStabilization_recorder: false
      using_jointState_recorder: true
      using_rosbag2: false
